POST http://localhost:3001/api/tasks
Content-Type: application/json

{
"description":"Task priva2",
"important":1,
"deadline":"2021-06-18T19:30",
"private":0,
"userid":1
}

###

PUT http://localhost:3001/api/tasks/2
Content-Type: application/json

{
"description":"Buy something big",
"important":1,
"deadline":"2021-06-29T19:30",
"private":0,
"userid":1
}

###

POST http://localhost:3001/api/tasks/3/1
Content-Type: application/json


###

DELETE http://localhost:3001/api/tasks/5